# Importacion de Módulos
from . import area_specialization
from . import res_partner
from . import patient
from . import initial_questionnarie
from . import sessions
from . import services
from . import complication_pregnancy
from . import habits_pregnancy
from . import birth_complications
from . import illnesses_types